# Generated by Django 3.2.23 on 2023-11-25 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='co_autor',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 52, 48, 200819)),
        ),
    ]
