# Generated by Django 3.2.23 on 2023-11-27 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_auto_20231125_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 7, 40, 14, 787259)),
        ),
    ]
